[tool.poetry]
name = "hw-12"
version = "0.1.0"
description = ""
authors = ["777Afanas <serhii2111@yahoo.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = ">=0.110.0"
uvicorn = {extras = ["standard"], version = ">=0.28.0"}
sqlalchemy = ">=2.0.0"
psycopg = {extras = ["binary"], version = ">=3.1.0"}
pydantic = {extras = ["email"], version = ">=2.6.0"}
pydantic-settings = ">=2.2.0"
python-dotenv = ">=1.0.0"
alembic = ">=1.13.0"
pyjwt = ">=2.8.0"
bcrypt = ">=4.0.0"
fastapi-mail = ">=1.4.0"
redis = ">=4.6.0,<5.0.0"
fastapi-limiter = "==0.1.6"
cloudinary = ">=1.38.0"
python-multipart = ">=0.0.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "sphinx (>=9.1.0,<10.0.0)",
    "requests (>=2.34.2,<3.0.0)"
]
